spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/donation_inventory}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
