spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5440/donation_inventory}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
